{
  "sksl": {
    "entrypoint": "drop_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float u_dropTime;\nuniform vec2 u_size;\nuniform vec2 u_center;\nuniform float u_useBefore;\nuniform vec3 u_col;\nuniform shader u_before;\nuniform half2 u_before_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    float dist = length(FLT_flutter_local_FlutterFragCoord() - u_center);\n    float maxDist = max(length(u_size - u_center), length(u_center));\n    float progression = (u_dropTime * 1.0) * (maxDist + 28.0);\n    float intensity = 1.0 - (dist / maxDist);\n    float strength = max(0.0, 1.0 - (abs(dist - progression) / 28.0));\n    fragColor = (vec4(u_col, 1.0) * strength) * intensity;\n    vec4 beforeCol = u_before.eval(u_before_size * ( FLT_flutter_local_FlutterFragCoord() / u_size));\n    if (((dist - progression) > 0.0) && (u_useBefore > 0.0))\n    {\n        fragColor = beforeCol;\n    }\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "u_dropTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "u_size",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "u_center",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "u_useBefore",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 4,
        "name": "u_before",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "u_col",
        "rows": 3,
        "type": 10
      }
    ]
  }
}